# @package _global_
model:
  name: EEGNet
  baseline:
    _target_: src.models.baselines.EEGNet
    n_channels: null
    n_samples: null
    n_classes: 3
    F1: 8
    D: 2
    F2: null
    kernel_length: 64
    separable_length: 16
    dropout: 0.25
  optimizer:
    learning_rate: 0.001
    weight_decay: 0.0001
  batch_size: 128
  max_epochs: 30
