# @package _global_
dataset:
  _target_: src.data.SyntheticEEGDatasetCollection   # Will be dynamically instantiated
  name: eeg_sim
  coeff: ???
  chemo_coeff: ${dataset.coeff}                         # Confounding coefficient of chemotherapy
  radio_coeff: ${dataset.coeff}                         # Confounding coefficient of radiotherapy
  seed: ${exp.seed}
  num_patients:
    train: 10000
    val: 1000
    test: 1000
  window_size: 15                                       # Used for biased treatment assignment
  lag: 0                                                # Lag for treatment assignment window
  max_seq_length: 60                                    # Max length of time series
  projection_horizon: 5                                 # Range of tau-step-ahead prediction (tau = projection_horizon + 1)
  cf_seq_mode: sliding_treatment                        # sliding_treatment / random_trajectories
  val_batch_size: 512                                   # Batch size for evaluation
  treatment_mode: multilabel                            # multiclass / multilabel -- for RMSN
  label_names: ["mauvais","moyen","excellent"]

model:
  dim_treatments: 2
  dim_vitals: 0
  dim_static_features: 1
  dim_outcomes: 3                                       # Number of outcome variables to predict (Mauvais, Bien, Excellent)
  dim_outcomes_input: 1                                 # Number of outcome variables as input (previous outcomes)

exp:                                                    # Both False for Classification and True for Regression
  unscale_rmse: False
  percentage_rmse: False
